name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install_test_deps
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: run_tests
      working-directory: test
      run: |
        make
      continue-on-error: false
      id: makefile

    - name: report_tests_result
      run: |
        if [ '${{ steps.makefile.outcome }}' == 'success' ]; then
          echo "Tests passed :-)"
          exit 0
        else
          echo "Tests failed :-("
          exit 1
        fi
