name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Run Makefile
      working-directory: test
      run: |
        make build
        make run
      continue-on-error: false
      id: makefile

    # - name: Check Result
    #   run: |
    #     if [ ${{ steps.makefile.outcome }} == 'success' ]; then
    #       echo "Tests passed :-)"
    #       exit 0
    #     else
    #       echo "Tests failed :-("
    #       exit 1
    #     fi
