name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Run tests
      working-directory: test
      run: make -s
      id: makefile

    - name: Report test results
      if: always()
      run: |
        if [ '${{ steps.makefile.outcome }}' == 'success' ]; then
          echo "\033[1;32mTests passed :-)\033[0m"
          exit 0
        else
          echo "\033[1;31mTests failed :-(\033[0m"
          exit 1
        fi
